### ISSUE TITLE
Publish Queue not loading on Sitecore 9.0 - 9.3

### ISSUE THREAD

**Issue by bmbruno** [bmbruno/SitecoreSpark.Admin.PublishQueueDetail#1]
Report page loads, but publish queue shows 0 items.

**Comment by bmbruno** [comment]
User error. Items must have workflow assigned to show up on this report.

**Comment by marcelgruber** [comment]
@bmbruno is there a way to get this working for items that do not have workflow states?

**Comment by bmbruno** [comment]
@marcelgruber This report is intended to show items in a Final Workflow state, so an assigned workflow is highly recommended. You could remove the workflow-related lines that filter out Final Workflow state on items (lines 66 - 73 and line 86), but you will get a much larger, more jumbled report.
